# Enable Fedora-style soft-peak limiting and optimal resampling quality in PipeWire
context.properties = {
    resample.quality = 4
    resample.peaks = true
    default.clock.rate = 48000
    default.clock.allowed-rates = [ 44100, 48000, 88200, 96000 ]
}
